version: '3'
services:
  chef-server:
    image: xfrarod/chef-server:v1
    container_name: chef-server
    ports:
      - "8088:80"
      - "443:443"
    command: /usr/bin/chef-server-ctl reconfigure
    entrypoint: /bin/bash -e /usr/local/bin/run.sh
    networks:
       - chefnetwork

  chef-node:
    image: xfrarod/chef-node:v1
    container_name: chef-node
    command: tail -F anything
    depends_on:
      - "chef-server"
    networks:
       - chefnetwork

  jenkins-master:
    image: xfrarod/jenkins-master
    container_name: jenkins-master
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
    environment:
      ADMIN_PASSWORD: admin
      ADMIN_USER: admin123
    networks:
      - chefnetwork

  jenkins-slave:
    image: xfrarod/jenkins-slave
    container_name: jenkins-slave
    depends_on:
      - "jenkins-master"
      - "chef-server"
    environment:
      - USER_NAME_SECRET=admin
      - PASSWORD_SECRET=admin123
      - COMMAND_OPTIONS=-master http://127.0.0.1:8080 ${AGENT_LABELS} -executors 4 -name jenkins-slave
    volumes:
      - workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    extra_hosts:
      - 'chef-server:127.0.0.1'
#    networks:
#      - chefnetwork
#    links:
#     - jenkins-master

#configs:
#  my_config:
#    file: ./my_config.txt
#  my_other_config:
#    external: true

#networks:
#  default:
#    external:
#      name: chefnetwork

networks:
  chefnetwork:
    external: false

volumes:
  jm:
  jmshare:
  workspace:
